language: node_js
node_js:
- 7
- 6
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - node_modules
before_install:
- npm install npm@5 -g
- npm cache verify
- npm prune
- npm update
install:
- npm install
after_install:
- 'echo "echoing in after_install steps" '
before_script:
- npm rebuild node-sass
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run test
after_success:
  - "curl -o /tmp/travis-automerge https://gist.githubusercontent.com/Nirajkashyap/dc9782229cd10cb7d3b6732f928d7d7a/raw/b0bf72adab7dabd8d44bf8e47b5c236d1030a34c/travis-automerge"
  - "chmod a+x /tmp/travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='develop' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=cdown/srt /tmp/travis-automerge"

env:
  global:
  - secure: cjSbs+51rGnIQeUV/2ekYdZ3uC+k25i5gQittuULyzJrgXMMmBl1p0T1bbC6f2xVBjKmPb09iO7jRK9wAKheD2DXI+boOXk6kppUrVRsKLGqUMVCweAa9wsdi4u8JoW9mGqJCypl0y5T/b7iJYGvHCJLadsET9mvyYCNHM63GRM=
  - secure: R3O/O5BskbWFSqSN9G1x1EDo83MHiyLue0GVMf5cCV+eiJHkag0A7cxYVGpoWzTx+t1UArMIpGLSzuIMiBpnLsR0vjm3R8UWhYM1ruqJCqdDP1bmJ7uYKGlJau2xHG86fc+190ChSY1l5ipjyui60564Yp02scePbX1aXbQXGbY=
after_failure:
- echo "echoing in after_failure steps"
after_script:
- 'echo "echoing in after_script steps and will public coverage to coveralls"  '
- cat ./coverage/lcov.info | coveralls
before_deploy:
- test $TRAVIS_TEST_RESULT = 0 
deploy:
  provider: npm
  email: niraj38re@gmail.com
  tag: next

  api_key:
    secure: VfpkqyKjdEWxMrUBZkwg1S5WX9Ud8c4EUWYMbCG7o5m3l5tEbIZYecS99IeJ6BxXrjvsSuYwhUSdixQa3f8l8pBSdmxfVikRqw+iNd9R9Ft4rlOWxXAWTrge/EYpaEFNEGLSxnrh8zB+p3cdvGxZN7DxGWQq18CaTi4mpwBvq1k1cxFeGIZWgYf3U/OEpEXtBR/j8cbpKBfMO9P0PA/zuoyEOpWF6z47yk/2Cc/B3J2NLdICyOQQuBiB6xHG953ftpdpq8W6DFq72VjPWwIsR8fzpRo5YiTJ6rEEVDgqR+AFXj60jZmYNr4tIFEHDTR3m7UltAHFWzsy15js3b8LXVtFLVxm6wUmkqs4H1P0gTFH9saWrgWmwNwAN6vq2Ygluv4y1G/C93afJ0sdqGc2+3E/eEYr8ZsFZoeRAg4RF3qm7feaQyxCdlALkSqb15Qz086YcMoByPjGVRZCtmJ6Z0qnaVPUn05FjfYa/RB9NoaY5N1ATZMJpwstzdWFysvXEWq1lJa9bUXlzLCcLa8cvSDgUkMfAMZ5QB8RqGBI5gkhdVCNatnQiweK8YJQcvJLCJBXMah9bUubcRiKxa27HOXzmDykAI0c/KfFoIuZaXHGwZ7P0O+UmX4qixJHcX8W0xMUYt+A8L4AD37/NjhScEwknGgKABsvx402UalDUgw=
  tag: next
  on:
    repo: Nirajkashyap/generator-angular-2-lazy
    branch: master
    
